app/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('guanjia/', admin.site.urls),
    path('', include('base.urls', namespace='base')),
    path('_/', include('django.conf.urls.i18n')),
]

# js files translation
urlpatterns += (
    path('jsi18n/',
         JavaScriptCatalog.as_view(packages=['localejs.jscripti18n']),
         name='javascript-catalog'),
    
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

base/urls.py
from . import views
from django.urls import path, re_path
from django.contrib.auth import views as auth_views


app_name = 'base'
urlpatterns = [
# open for everyone
    path('', views.home_view, name = 'home'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='base/login.html'), name = 'login'),
    # re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #         views.activate_view, name='activate_account'),
    path('accounts/register/', views.register_view, name = 'register'),

    # # login_required
    path('account/logout/', views.logout_view, name = 'logout'),
    path('account/', views.account_view, name='account'),
    # path('myaccount/profile/update', views.update_profile_view, name='update_profile'),
    # path('myaccount/change-password/', views.change_password_view, name='change_password'),
]

base/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from django.utils.translation import ugettext_lazy as _

from django.urls import reverse

from django.db.models.signals import post_save

from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.validators import RegexValidator

from datetime import date

phone_regex = RegexValidator(regex=r'^\s*(?:\+?(\d{1,3}))?[-. (]*(\d{3})[-. )]*(\d{3})[-. ]*(\d{4})(?: *x(\d+))?\s*$', \
	message=_("Invalid phone number format. Enter as 1-123-456-7890."))

zip_regex = RegexValidator(regex=r'^[0-9]{2,6}(?:-[0-9]{4})?$|^$', message=_("Plese Enter a valid zip code."))


LANGUAGE_CATEGORY = (
	('EN', _('English')),
	('CN', _('Chinese')),
)

class User(AbstractUser):
	email = models.EmailField(blank=False, default='', unique=True, verbose_name = _("Email"))
	email_confirmed = models.BooleanField(default =False, verbose_name= _('Email Confirmed'))
	email_confirmed.boolean = True

	phone = models.CharField(validators=[phone_regex], max_length=16, blank=True, default='',verbose_name= _('Phone Number'))
	default_address = models.ForeignKey('Address', on_delete=models.SET_NULL, blank=True, null=True,  related_name='default_address', verbose_name= _('Default Shipping Address'))

	reward = models.PositiveIntegerField(default = 0, verbose_name= _('Reward Points'))
	birthday = models.DateField(blank=True, null=True,verbose_name= _('Birthday'))
	updated_date = models.DateTimeField(auto_now = True, blank=True, null=True, verbose_name=_('Profile Updated Date'))
	country = models.CharField(max_length=100, blank=True, default='',verbose_name= _('Country'))
	language = models.CharField(max_length=100, choices=LANGUAGE_CATEGORY,  blank=True, default='',verbose_name= _('Preferred Language'))
	privacy_policy_agree = models.BooleanField(default =False, verbose_name= _('Privacy Policy Agreement'))
	memo = models.TextField(blank = True, default='', verbose_name= _('Memo'))

	def __str__(self):
		if self.first_name and self.last_name:
			return '%s %s: %s'%(self.first_name, self.last_name, self.email)
		else:
			return '%s : %s'%(self.username, self.email)


	class Meta(AbstractUser.Meta):
		verbose_name_plural = _("Users")
		ordering = ['-id']

class Address_Common_Info(models.Model):
	created_date = models.DateTimeField(auto_now_add = True, blank=True, null=True, verbose_name= _('Creation Date'))
	address = models.CharField(max_length=500, default='',verbose_name=_('address'))
	apt = models.CharField(blank=True, max_length=200, default='',verbose_name=_('Address2/Apartment'))
	city = models.CharField(max_length=100, default='',verbose_name= _('City'))
	state = models.CharField(max_length=100, default='',verbose_name= _('State/Province'))
	country = models.CharField(max_length=100, default='',verbose_name=_( 'Country'))
	zipcode = models.CharField(max_length=12, validators=[zip_regex], default='', verbose_name= _('Zip Code'))
	memo = models.TextField(blank = True, default='', verbose_name= _('Memo'))

	class Meta:
		abstract = True

class Address(Address_Common_Info):
	updated_date = models.DateTimeField(auto_now = True, blank=True, null=True, verbose_name= _('Address Updated Date'))
	user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, verbose_name= _('User'))
	first_name = models.CharField(max_length=100, default='',verbose_name= _('First Name'))
	last_name = models.CharField(max_length=100, default='',verbose_name= _('Last Name'))
	phone = models.CharField(validators=[phone_regex], max_length=16, default='',verbose_name= _('Phone Number'))

	class Meta:
		verbose_name_plural = _("Addresses")
		unique_together=('user',
		'first_name',
		'last_name',
		'phone',
		'address',
		'apt',
		'city',
		'state',
		'zipcode'
		)

class Notic(models.Model):
	created_date = models.DateTimeField(auto_now_add = True, blank=True, null=True, verbose_name= _('Creation Date'))
	open = models.BooleanField(default =False, verbose_name= _('Open Notic'))
	open.boolean = True
	text = models.TextField(max_length = 1000, blank=True, default='', verbose_name= _('notic text'))
	image_url =  models.CharField(max_length = 1000, blank=True, default='', verbose_name = _('notic image URL'))

base/forms.py
from django import forms
from .models import (
	User, Address, phone_regex, zip_regex, LANGUAGE_CATEGORY
	)

from django.utils.translation import gettext as _
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.utils.translation import ugettext_lazy as _

import datetime

year = datetime.datetime.now().year
birthday_years = [i for i in range(year-100,year)]

class NewUserCreationForm(UserCreationForm):
	birthday = forms.DateField(required = False, widget=forms.SelectDateWidget(
						empty_label=("YYYY", "MM", "DD"),
					years = birthday_years))
	class Meta(UserCreationForm.Meta):
		model = User
		fields = ('username', 'email', 'first_name', 'last_name',
					'phone', 'country', 'language', 'birthday', 'password1', 'password2', 'privacy_policy_agree')

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		# self.fields['birthday'].label = _('Birthday')
		self.fields['country'].initial = 'USA'
		self.fields['phone'].validators = [phone_regex]
		self.fields['language'].choices = LANGUAGE_CATEGORY
		self.fields['phone'].widget.attrs['placeholder'] = _('+1-234-567-8900')
		self.fields['privacy_policy_agree'].required = True

	def save(self, commit=True, *args, **kwargs):
		user = super(NewUserCreationForm, self).save(commit=False, *args, **kwargs)
		user.first_name = user.first_name.title()
		user.last_name = user.last_name.title()
		user.email = user.email.lower()
		if commit:
			user.save()
		return user

class NewUserChangeForm(UserChangeForm):
	birthday = forms.DateField(required = False, widget=forms.SelectDateWidget(
				empty_label=("YYYY", "MM", "DD"),
				years = birthday_years))

	class Meta:
		model = User
		fields = ('username', 'email', 'first_name', 'last_name',
					'phone', 'country', 'language', 'birthday',
					'default_address', 'password',)

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['birthday'].label = _('Birthday')
		self.fields['country'].initial = 'USA'
		self.fields['phone'].validators = [phone_regex]
		self.fields['language'].choices = LANGUAGE_CATEGORY
		self.fields['phone'].widget.attrs['placeholder'] = _('+1-234-567-8900')
		if self.instance:
			try:
				user = User.objects.get(id = self.instance.id)
				if user.email_confirmed:
					self.fields['email'].widget.attrs['readonly'] = True
				if user.birthday:
					self.fields['birthday'].widget.attrs['readonly'] = True
			except:
				pass

	def save(self, commit=True, *args, **kwargs):
		user = super(NewUserChangeForm, self).save(commit=False, *args, **kwargs)
		user.first_name = user.first_name.title()
		user.last_name = user.last_name.title()
		user.email = user.email.lower()
		if commit:
			user.save()
		return user


class AddressForm(forms.ModelForm):

	class Meta:
		model = Address
		exclude = ('meno',)

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['apt'].widget.attrs['placeholder'] = _('Apartment/Suit/Unit')
		self.fields['phone'].widget.attrs['placeholder'] = _('+1-234-567-8900')
		self.fields['phone'].validators = [phone_regex]
		self.fields['address'].widget.attrs['placeholder'] = _('Street Address')


	def save(self, commit=True, *args, **kwargs):
		add = super(AddressForm, self).save(commit=False, *args, **kwargs)
		add.first_name = add.first_name.title()
		add.last_name = add.last_name.title()
		add.address = add.address.title()
		add.apt = add.apt.title()
		add.city = add.city.title()
		add.state = add.state.title()
		if commit:
			add.save()
		return add

base/views.py
from django.conf import settings
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import TemplateView
from django.contrib.auth import update_session_auth_hash, authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _

from .models import User, Address, Notic
from .forms import NewUserChangeForm, NewUserCreationForm, AddressForm
from .code import get_contexts, send_confirmation_email

def home_view(request):
	template_name = 'base/home.html'
	return render(request, template_name)

@login_required
def account_view(request):
	template_name = 'base/account.html'
	contexts = get_contexts(request)
	return render(request, template_name, contexts)

@login_required
def logout_view(request):
	logout(request)
	return redirect(reverse('base:home'))

def register_view(request):
	if request.user.is_authenticated:
		return redirect(reverse('base:account'))

	template_name = 'base/register.html'
	txt = get_contexts(request)

	if request.method == 'POST':
		form = NewUserCreationForm(request.POST)
		if form.is_valid():
			user = form.save()
			try:
				send_confirmation_email(request, user)
				messages.info(request, _('Confirmation link was sent successfully. Please check your email!'))
			except:
				messages.error(request, _('Confirmation link was fail to send! Please double check your emaill address!'))


			username = request.POST['username']
			password = request.POST['password1']
			login_user = authenticate(
				username = username,
				password = password
			)
			login(request, login_user)
			return redirect(reverse('base:account'))
		else:
			txt['form'] = form
			return render(request, template_name, txt)
	else:
		form = NewUserCreationForm()
		txt['form'] = form
		return render(request, template_name, txt)


# def activate_view(request, uidb64, token, backend='django.contrib.auth.backends.ModelBackend'):
# 	try:
# 		uid = force_text(urlsafe_base64_decode(uidb64))
# 		user = User.objects.get(pk=uid)
# 	except(TypeError, ValueError, OverflowError, User.DoesNotExist):
# 		user = None
# 	if user is not None and account_activation_token.check_token(user, token):
# 		user.is_active = True
# 		user.email_confirmed = True
# 		user.save()
# 		return redirect('account')
# 	else:
# 		return HttpResponse('Activation link is invalid!')

# def update_profile_view(request):
# 	template_name = 'main/updateprofile.html'
# 	txt = get_contexts(request)
# 	if request.method == 'POST':
# 		form = NewUserChangeForm(request.POST, instance=request.user)
# 		form.fields['password'].required = False
# 		if form.is_valid():
# 			user = form.save()
# 			return redirect(reverse('base:account'), txt, user = user)
# 		else:
# 			txt +={'form': form}
# 			return render(request, template_name, txt)
# 	else:
# 		form = NewUserChangeForm(instance=request.user)
# 		form.fields['password'].required = False
# 		txt +={'form': form}
# 		return render(request, template_name, txt)

# def change_password_view(request):
# 	template_name = 'main/changepassword.html'
# 	txt = get_contexts(request)
# 	if request.method == 'POST':
# 		form = PasswordChangeForm(request.POST, instance=request.user)
# 		if form.is_valid():
# 			form.save()
# 			update_session_auth_hash(request, form.user)
# 			return redirect(reverse('base:account'))
# 		else:
# 			txt +={'form': form}
# 			return render(request, template_name, txt)
# 	else:
# 		form = PasswordChangeForm(instance=request.user)
# 		form.fields['password'].required = False
# 		txt +={'form': form}
# 		return render(request, template_name, txt)


# def send_email_view(request):
# 	if request.method == 'POST':
# 		email = EmailForm(request.POST)
# 		if email.is_valid():
# 			user_email = email.cleaned_data['email'].lower()
# 			subject = _('Contact us - ') + email.cleaned_data['subject']
# 			content = _('User Email: ') + user_email + '\n' + email.cleaned_data['content']
# 			to_email = settings.support_email
# 			if email.cleaned_data['cc']:
# 				to_email.append(user_email)

# 			send_mail(
# 					subject,
# 					content,
# 					settings.DEFAULT_FROM_EMAIL,
# 					to_email,
# 					fail_silently=False,
# 				)
# 		if next and next!='':
# 			return redirect(next)
# 		else:
# 			return redirect(reverse('base:home'))

base/templates/base/account.html
{% extends "base/base.html" %}
{% load i18n static %}


{% block content %}
<div class="w3-panel w3-margin-top content_center">
	<div class="text-xxlarge-bold">{{user.username}}{% trans "'s Profile" %}</div>
</div>
<hr/>
<div class="w3-panel content_center">
	<div class = "w3-container">
		{% trans 'First Name' %}: {{user.first_name}}<br/>
		{% trans 'Last Name' %}: {{user.last_name}}<br/>
		{% trans 'Email address' %}: {{user.email}}

		{% if not user.email_confirmed %}
			<br/><a href="#">
				{% trans "You havn't confirmed your email yet. Please click here to send a Confirmation link to your email." %}
			</a></br/>
		{% else %}
			<span>({% trans 'email confirmed' %})</span><br/>
		{% endif %}

		{% trans 'Phone Number' %}: {{user.phone}}<br/>
		{% trans 'Birthday' %}: {{user.birthday|date:"M d, Y" }}<br/>
		{% trans 'Country' %}: {{user.country }}<br/>

		{% trans 'Preferred language' %}:{{ user.get_language_display }}<br/>
		<div class="text-regular-bold w3-padding-16">{% trans 'Default Address' %}</div>

		{% if user.default_address %}
					{% include "blocks/default_address_card.html" with add=user.default_address%}
		{% else %}
				{% trans 'No default address!' %}
		{% endif %}
		<div class="w3-row">
			<button class="logo-red" type = "button" onclick="window.location.href = '#'">{% trans 'Update Profile' %}</button>
			<button class="logo-blue" type = "button" onclick="window.location.href = '#'">{% trans 'Change Password' %}</button>
		</div>
</div>
{% endblock %}

base/templates/base/base.html
{% load i18n static compress %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    {% block blockbots %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="FIND it OVERSEAS provides Consolidated Transportation Service">
    <meta name="keywords" content="Consolidated Transportation Service, Co-shipping, Direct Shipping, Shipping from China, ">
    <meta name="author" content="Cuishan Liu">
    {% endblock %}

    
    <title>{% block title %}{{title}}{% endblock %} | {% trans 'Consolidated Transportation Service from FIND it OVERSEAS' %}</title>
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    {% block extrahead %}{% endblock %}


    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>
    <script src="/jsi18n"></script>
    <script src="{% static 'js/base.js' %}"></script>

    <!-- <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> -->
    <!-- for fa fa icon -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        
    {% compress css %}
        <link type="text/x-scss" href="{% static 'styles/index.scss' %}" rel="stylesheet" media="screen">
        <link type="text/x-scss" href="{% static 'styles/style.scss' %}" rel="stylesheet" media="screen">
        {% block extrastyle %}{% endblock %}
        {% block responsive %}{% endblock %}
    {% endcompress %}

</head>

<body>
    {% block header %}
        <!-- Header -->
        <div class="header">
            <div class="header-brand">
                <a href="{% url 'base:home' %}" class="header-brand__a">
                    <img src="{% static 'images/brand.cst.png' %}" alt="logo" class="header-brand__a__img">
                </a>
            </div>
            <div class="header-menu">
                <a class="header-menu__a" href="{% url 'base:home'%}">{% trans "Price List" %}</a>
                {% if user.is_authenticated %}
                    <div class="header-menu-dropdown">
                        {{user.username}}
                        <i class="header-menu-dropdown__i fa fa-caret-down"></i>
                        <div class="header-menu-dropdown-content profile-links">
                            <a class="header-menu-dropdown-content__a" href="{% url 'base:account' %}">{% trans "Profile" %}</a>
                            <a class="header-menu-dropdown-content__a" href="{% url 'base:home' %}">{% trans "Address Book" %}</a>
                            <a class="header-menu-dropdown-content__a" href="{% url 'base:home' %}">{% trans "Packages History" %}</a>
                            <a class="header-menu-dropdown-content__a" href="{% url 'base:home' %}">{% trans "Wallet" %}</a>
                            <a class="header-menu-dropdown-content__a" href="{% url 'base:logout' %}">{% trans "Log Out" %}</a>
                        </div>
                    </div>
                {% else %}
                    <a class="header-menu__a" href="{% url 'base:login' %}"><span class="logo-text-blue" >{% trans "Log in" %}</span></a>
                    <a class="header-menu__a" href="{% url 'base:register' %}"><span class="logo-text-red" >{% trans "Sign Up" %}</span></a>
                {% endif %}

                <div class="header-menu-dropdown">
                    Language/语言
                    <i class="header-menu-dropdown__i fa fa-caret-down"></i>
                    <div class="header-menu-dropdown-content languages">
                        <form class="header-menu-dropdown-content__form" action="/_/setlang/" method="post">
                            {% csrf_token %}
                            <input name="next" type="hidden" value="{{ redirect_to }}"/>
                            <select name="language" class="header-menu-dropdown-content__select language__select" onchange="this.form.submit()">
                                    <option class="header-menu-dropdown-content__select__option language__select__option" value="en-us">English</option>
                                    <option class="header-menu-dropdown-content__select__option language__select__option" value="zh-Hans">简体中文</option>
                            </select>
                        </form>
                    </div>
                </div>
                
                <a class="header-menu-icon__a" href="javascript:void(0);" class="icon" onclick="openMenu()">
                    <i class="header-menu-icon__a__i fa fa-bars"></i>
                </a>
            </div>
        </div>
        <!-- END Header -->
    
        {% block notic %}
            {% if notic %}
            {% endif %}
        {% endblock %}
    {% endblock %}


    {% block messages %}
        {% if messages %}
        <ul class="messagelist__ul">{% for message in messages %}
            <li{% if message.tags %} class="messagelist__ul__li {{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock %}



    <!-- Content -->
    <div class="content {% block contentClass %}{% endblock %}">
        {% block sidebar_right %}{% endblock %}
        {% block content_title %}{% if title %}<div class="content-title">{{ title }}</div>{% endif %}{% endblock %}
        {% block content %}{% endblock %}
        {% block sidebar_left %}{% endblock %}
    </div>
    <!-- END Content -->

    {% block footer %}
        <div class="footer">
            <span class="footer-copyright">
                &copy; 2019 {% trans "All Rights Reserved" %}
            </span>
            <span class="footer-policy">
                {% trans "Privacy Policy" %} | {% trans "Terms of Service" %}
            </span>
        </div>
    {% endblock %}
</body>

</html>

base/templates/base/changepassword.html
{% extends "main/base.html" %}
{% load i18n static %}

{% block content %}
<div class="w3-container content_center">
    <form method="post">
        {% csrf_token %}

        {% if form.errors %}
            <p class="errornote">
            {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
            </p>
        {% endif %}


        <p>{% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}</p>

        <div class="w3-panel">
            <div class="w3-row">
                {{ form.old_password.label_tag }} {{ form.old_password }}  {{ form.old_password.errors}}
            </div>

            <div class="w3-row">
                {{ form.new_password1.label_tag }} {{ form.new_password1 }} {{ form.new_password1.errors }}
            </div>

        {% if form.new_password1.help_text %}
            <div class="help">{{ form.new_password1.help_text|safe }}</div>
        {% endif %}

        <div class="w3-row">
            {{ form.new_password2.label_tag }} {{ form.new_password2 }}  {{ form.new_password2.errors }}
        </div>

        {% if form.new_password2.help_text %}
        <div class="help">{{ form.new_password2.help_text|safe }}</div>
        {% endif %}

      </div>

        <div class="w3-row">
            <button type="button" class="cancel_btn" onclick="window.location.href = document.referrer">{% trans 'Cancel' %}</button>
            <input type="submit" class="save_btn" value="{% trans 'Change my password' %}"/>
        </div>
    </form>
</div>

{% endblock %}

base/templates/base/customer_service.html
{% extends "main/base_site.html" %}
{% load i18n static %}

{% block contentClass %}tracking_page{% endblock %}
{% block content %}
<div class="w3-center w3-padding-32 w3-margin-top" style="height:200px;" id="customer_service_block">

<img src="{% static 'image/logo_circle_big.png' %}" alt="logo" style="width:200px; margin:auto;"/>
<div class="text-regular-bold w3-text-white w3-padding-16">{% trans 'Express - Modern Transport & Logistics' %}</div>

</div>
<div class="w3-panel content_center">
<table id="customer_service_table">
  <tr class="w3-row">
    <th class="w3-quarter">
      <img src="{% static 'image/global-shop.png' %}" alt="global shop"/>
    <a href="{% url 'shopping' %}">  <div class="text-regular-bold w3-text-black">{% trans 'Global Shop' %}</div></a>
    </th>
    <th class="w3-quarter">
      <img src="{% static 'image/collection-points.png' %}" alt="collection points" />
    <a href="{% url 'information' 'collection_points' %}">   <div class="text-regular-bold  w3-text-black">{% trans 'Collection Points' %}</div></a>
    </th>
    <th class="w3-quarter">
      <img src="{% static 'image/shipping.png' %}" alt="shipping" />
      <a href="{% url 'information' 'coshipping_guide' %}">   <div class="text-regular-bold  w3-text-black">{% trans 'Co-Shipping' %}</div></a>
    </th>
    <th class="w3-quarter">
      <img src="{% static 'image/users-collectors.png' %}" alt="users-collectors"/>
      <a href="{% url 'information' 'use_guide' %}">   <div class="text-regular-bold  w3-text-black">{% trans 'Users and Collectors' %}</div></a>
    </th>
  </tr>
  <tr class="w3-row">
    <th class="w3-quarter">
      <img src="{% static 'image/reward-points.png' %}" alt="reward points" />
        <a href="{% url 'information' 'reward_points' %}">   <div class="text-regular-bold  w3-text-black">{% trans 'Reward Points' %}</div></a>
    </th>
    <th class="w3-quarter">
      <img src="{% static 'image/return-policy.png' %}" alt="return policy" />
      <a href="{% url 'information' 'return_policy' %}">   <div class="text-regular-bold  w3-text-black">{% trans 'Return Policy' %}</div></a>
    </th>
    <th class="w3-quarter">
      <img src="{% static 'image/contact-us.png' %}" alt="contact us"/>
      <a href="{% url 'information' 'contact' %}">   <div class="text-regular-bold  w3-text-black">{% trans 'Contact Us' %}</div></a>
    </th>
    <th class="w3-quarter">
      <img src="{% static 'image/faqs.png' %}" alt="FAQs"/>
      <a href="{% url 'information' 'faqs' %}">   <div class="text-regular-bold  w3-text-black">{% trans 'FAQs' %}</div></a>
    </th>
  </tr>
</table>



</div>
{% endblock %}

base/templates/base/login.html
{% extends "base/base.html" %}
{% load i18n static compress %}

{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static "styles/login.scss" %}" />
{% endblock %}

{% block header %}{% endblock %}
{% block content_title %}{% endblock %}
{% block contentClass %} login {% endblock %}

{% block content %}
{% if form.errors and not form.non_field_errors %}
<p class="errornote">
{% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
</p>
{% endif %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class="errornote">
    {{ error }}
</p>
{% endfor %}
{% endif %}

<div id="content-main" class="w3-container">
    <div class="w3-padding-32 w3-center">
        <a href="{% url 'base:home' %}">
            <img src="{% static 'images/brand.cst.png' %}" alt="logo" style="height:150px; margin:auto;">
        </a>
    </div>

    {% if user.is_authenticated %}
    <p class="errornote">
      {{user.username}},&nbsp;
      {% blocktrans trimmed %}
          you are not authorized to access this page. Would you like to login to a different account?
      {% endblocktrans %}
    </p>
    {% endif %}

    <form action="{{ app_path }}" method="post" id="login-form">{% csrf_token %}
      <div class="w3-row">
        {{ form.username.label_tag }} {{ form.username.errors }} {{ form.username }}
      </div>
      <div class="w3-row">
        {{ form.password.label_tag }} {{ form.password.errors }} {{ form.password }}
        <input type="hidden" name="next" value="{{ next }}" />
      </div>
      <div class="w3-row">
          <a href="{% url 'base:register' %}"><span class="logo-text-red" >{% trans "Sign Up" %}</span></a>
        <div class="w3-right">
        </div>
      </div>
      <div class="w3-center">
        <input id="login_btn" class="logo-blue"  type="submit" value="{% trans 'Log in' %}" />
      </div>
    </form>

</div>

{% endblock %}

base/templates/base/wallet.html
{% extends "main/base_site.html" %}
{% load i18n static %}

{% block title%}
{{user.username}}{% trans "'s Wallet" %}
{% endblock%}

{% block content %}
<div class="content_center">
  <h2>
    <img src="{% static 'image/reward-points.png' %}" alt="reward_points" height="50px" width="50px"/>
    {% trans " Reward Points" %}: {{user.reward}}
  </h2>
</div>
{% endblock %}